name: KissExcel-CI

on:
  push:
    branches:
    - master
env:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: dotnet build KissExcel/KissExcel.csproj --configuration ${{ env.buildConfiguration }}
    - run: dotnet test KissExcel.Test/KissExcel.Test.csproj
    - run: dotnet publish KissExcel/KissExcel.csproj
